[2025-02-27T21:34:55.030+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T21:34:55.057+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_and_transform.create_table_canada manual__2025-02-27T21:34:00.844211+00:00 [queued]>
[2025-02-27T21:34:55.069+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_and_transform.create_table_canada manual__2025-02-27T21:34:00.844211+00:00 [queued]>
[2025-02-27T21:34:55.069+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-27T21:34:55.087+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): create_table_canada> on 2025-02-27 21:34:00.844211+00:00
[2025-02-27T21:34:55.095+0000] {standard_task_runner.py:72} INFO - Started process 5897 to run task
[2025-02-27T21:34:55.103+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_and_transform', 'create_table_canada', 'manual__2025-02-27T21:34:00.844211+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/transformation.py', '--cfg-path', '/tmp/tmpd3c452lq']
[2025-02-27T21:34:55.107+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask create_table_canada
[2025-02-27T21:34:55.165+0000] {task_command.py:467} INFO - Running <TaskInstance: load_and_transform.create_table_canada manual__2025-02-27T21:34:00.844211+00:00 [running]> on host airflow.us-central1-c.c.healthcare-project-452218.internal
[2025-02-27T21:34:55.237+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_and_transform' AIRFLOW_CTX_TASK_ID='create_table_canada' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T21:34:00.844211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T21:34:00.844211+00:00'
[2025-02-27T21:34:55.240+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T21:34:55.267+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-02-27T21:34:55.268+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-02-27T21:34:55.268+0000] {credentials_provider.py:409} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-02-27T21:34:55.280+0000] {bigquery.py:2956} INFO - Executing: {'query': {'query': "\n                        CREATE OR REPLACE TABLE `healthcare-project-452218.transform_dataset.canada_table` AS\n                        SELECT *\n                        FROM `healthcare-project-452218.staging_dataset.global_data`\n                        WHERE country = 'Canada'\n                    ", 'useLegacySql': False}}'
[2025-02-27T21:34:55.289+0000] {bigquery.py:1344} INFO - Inserting job airflow_load_and_transform_create_table_canada_2025_02_27T21_34_00_844211_00_00_ec71a2ff412ccd7925d92bbd65b93928
[2025-02-27T21:34:55.483+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 3033, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US; reason: notFound, message: Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US

Location: US
Job ID: airflow_load_and_transform_create_table_canada_2025_02_27T21_34_00_844211_00_00_ec71a2ff412ccd7925d92bbd65b93928

[2025-02-27T21:34:55.493+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=load_and_transform, task_id=create_table_canada, run_id=manual__2025-02-27T21:34:00.844211+00:00, execution_date=20250227T213400, start_date=20250227T213455, end_date=20250227T213455
[2025-02-27T21:34:55.520+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T21:34:55.520+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task create_table_canada (404 Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US; reason: notFound, message: Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US

Location: US
Job ID: airflow_load_and_transform_create_table_canada_2025_02_27T21_34_00_844211_00_00_ec71a2ff412ccd7925d92bbd65b93928
; 5897)
Traceback (most recent call last):
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 3033, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US; reason: notFound, message: Not found: Dataset healthcare-project-452218:transform_dataset was not found in location US

Location: US
Job ID: airflow_load_and_transform_create_table_canada_2025_02_27T21_34_00_844211_00_00_ec71a2ff412ccd7925d92bbd65b93928

[2025-02-27T21:34:55.557+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-27T21:34:55.588+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T21:34:55.589+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
