[2025-02-27T21:00:19.439+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T21:00:19.453+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gcs_to_bq.load_csv_to_bq manual__2025-02-27T21:00:14.633384+00:00 [queued]>
[2025-02-27T21:00:19.461+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gcs_to_bq.load_csv_to_bq manual__2025-02-27T21:00:14.633384+00:00 [queued]>
[2025-02-27T21:00:19.461+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-27T21:00:19.480+0000] {taskinstance.py:2890} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_to_bq> on 2025-02-27 21:00:14.633384+00:00
[2025-02-27T21:00:19.486+0000] {standard_task_runner.py:72} INFO - Started process 5420 to run task
[2025-02-27T21:00:19.499+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_gcs_to_bq', 'load_csv_to_bq', 'manual__2025-02-27T21:00:14.633384+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/load_to_str_to_bigquery.py', '--cfg-path', '/tmp/tmp28onv2qx']
[2025-02-27T21:00:19.504+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask load_csv_to_bq
[2025-02-27T21:00:19.577+0000] {task_command.py:467} INFO - Running <TaskInstance: load_gcs_to_bq.load_csv_to_bq manual__2025-02-27T21:00:14.633384+00:00 [running]> on host airflow.us-central1-c.c.healthcare-project-452218.internal
[2025-02-27T21:00:19.663+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_gcs_to_bq' AIRFLOW_CTX_TASK_ID='load_csv_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T21:00:14.633384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T21:00:14.633384+00:00'
[2025-02-27T21:00:19.665+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T21:00:19.702+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-02-27T21:00:19.702+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-02-27T21:00:19.703+0000] {gcs_to_bigquery.py:387} INFO - Using existing BigQuery table for storing data...
[2025-02-27T21:00:19.704+0000] {credentials_provider.py:409} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-02-27T21:00:19.719+0000] {gcs_to_bigquery.py:391} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'healthcare-project-452218', 'datasetId': 'staging_dataset', 'tableId': 'global'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://bkt-src-global-health-data/global_health_data.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': True, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8', 'allowJaggedRows': True}}
[2025-02-27T21:00:19.730+0000] {bigquery.py:1344} INFO - Inserting job airflow_load_gcs_to_bq_load_csv_to_bq_2025_02_27T21_00_14_633384_00_00_86e9be68674f75fae32e19b34e6b06b4
[2025-02-27T21:00:20.403+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 456, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 969, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://bkt-src-global-health-data/global_health_data.csv; reason: notFound, message: Not found: URI gs://bkt-src-global-health-data/global_health_data.csv
[2025-02-27T21:00:20.416+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=load_gcs_to_bq, task_id=load_csv_to_bq, run_id=manual__2025-02-27T21:00:14.633384+00:00, execution_date=20250227T210014, start_date=20250227T210019, end_date=20250227T210020
[2025-02-27T21:00:20.445+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T21:00:20.446+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task load_csv_to_bq (404 Not found: URI gs://bkt-src-global-health-data/global_health_data.csv; reason: notFound, message: Not found: URI gs://bkt-src-global-health-data/global_health_data.csv; 5420)
Traceback (most recent call last):
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 456, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 969, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sravan2418/airflow-env/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://bkt-src-global-health-data/global_health_data.csv; reason: notFound, message: Not found: URI gs://bkt-src-global-health-data/global_health_data.csv
[2025-02-27T21:00:20.474+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-27T21:00:20.495+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T21:00:20.496+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
